# Generated by Django 5.0.7 on 2024-07-23 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='programme_id',
            field=models.ForeignKey(blank=True, db_column='programme_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.programme'),
        ),
    ]
