# Generated by Django 5.0.7 on 2024-07-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_login_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='no_of_bed',
            field=models.IntegerField(default=4),
        ),
    ]
