# Generated by Django 5.0.7 on 2024-07-27 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_room_no_of_bed'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='room_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.room'),
        ),
    ]
