# Generated by Django 5.0.7 on 2024-07-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_student_room_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='room_id',
            new_name='room',
        ),
    ]
